# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

gitpush(){
  cd ~/projects
  git pull
  git add -A
  COMMENT=${1:-(date +"[%Y-%m-%d %H:%M] $HOSTNAME $USER: push code")}
  git commit -m "$COMMENT"
  git push
}

