# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

alias gitpush=(
  cd ~/projects
  git pull
  git add -A
  git commit -am $(date +"[%Y-%m-%d %H:%M] $USER: push code")
  git push
)
