-- TEST TYP_CONFIG
DECLARE
    L_TYP_CONFIG    TYP_CONFIG := TYP_CONFIG('TEST CODE', 'TEST NAME', 'TEST VALUE', 'TEST TYPE');
BEGIN
    --INSERT INTO TAB_CONFIG VALUES(L_TYP_CONFIG);
    --L_TYP_CONFIG.PRC_PRINT_INFO();
    --TYP_CONFIG.PRC_PRINT_TYPE_INFO();
    PKG_CONFIG_UTIL.G_CONFIG := L_TYP_CONFIG;
    --PKG_CONFIG_UTIL.G_CONFIG.PRC_PRINT_INFO();
    PKG_CONFIG_UTIL.PRC_INS_INTO_TAB_CONFIG(L_TYP_CONFIG);
    --PKG_CONFIG_UTIL.G_CONFIG.PRC_PRINT_INFO();
    --EXECUTE IMMEDIATE 'INSERT INTO TAB_CONFIG VALUES(PKG_CONFIG_UTIL.G_CONFIG)';
END;
/

-- TEST PKG_CONFIG_UTIL
DECLARE
BEGIN
    PKG_CONFIG_UTIL.PRC_INIT_CONFIG();
END;
/

SELECT * FROM TAB_CONFIG;
/
INSERT INTO TAB_CONFIG VALUES(PKG_CONFIG_UTIL.G_CONFIG());